### ISSUE TITLE
Some datasets have not come with node labels

### ISSUE THREAD

**Issue by LvShengZe903** [chentingpc/gfn#6]
Some datasets with both node lables and graph lables can run the code successfully, but there are some datasets which have not come with node labels, when I run the code, exist a bug.
Traceback (most recent call last):
  File "main.py", line 306, in <module>
    run_exp_single_test()
  File "main.py", line 301, in run_exp_single_test
    run_exp_lib([('REDDIT-MULTI-12K', 'data', 'ResGFN')])
  File "main.py", line 189, in run_exp_lib
    logger=logger)
  File "/home/lvshengze/gfn-master/train_eval.py", line 110, in cross_validation_with_val_set
    model, optimizer, train_loader, device)
  File "/home/lvshengze/gfn-master/train_eval.py", line 198, in train
    out = model(data)
  File "/opt/anaconda3/envs/lsz/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvshengze/gfn-master/res_gcn.py", line 117, in forward
    return self.forward_BNConvReLU(x, edge_index, batch, xg)
  File "/home/lvshengze/gfn-master/res_gcn.py", line 140, in forward_BNConvReLU
    x = self.bn_feat(x)
  File "/opt/anaconda3/envs/lsz/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/opt/anaconda3/envs/lsz/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 85, in forward
    self._check_input_dim(input)
  File "/opt/anaconda3/envs/lsz/lib/python3.6/site-packages/torch/nn/modules/batchnorm.py", line 177, in _check_input_dim
    if input.dim() != 2 and input.dim() != 3:
AttributeError: 'NoneType' object has no attribute 'dim'

I have no idea to use torch_geometric.transforms.Constant or torch_geometric.transforms.OneHotDegree to add node labels to the datasets. 
Sincerely looking forward to your reply.

**Comment by Waterpine** [comment]
I apologize for my delayed response since I am busy recently. It seems that the latest version of PyTorch does not support our code. Could you use pytorch 1.0? because when we implement this project, the version PyTorch and torch_geometric are all very old. Thanks!

**Comment by LvShengZe903** [comment]
> I apologize for my delayed response since I am busy recently. It seems that the latest version of PyTorch does not support our code. Could you use pytorch 1.0? because when we implement this project, the version PyTorch and torch_geometric are all very old. Thanks!

I am really appreciate for your enduring reply. Thank you very much.
