### ISSUE TITLE
Why the FeatureExpander function got wrong to init?

### ISSUE THREAD

**Issue by Kevin-shihello-world** [chentingpc/gfn#8]
I want to do some tests on the GFN code. And I follow the lead but I want to just run on one dataset so I modified the run_exp_benchmark function and let it only run on the ENZYME dataset, and it warms me this (I also tried -test 's setting but it warmed me the same): 
```
python
Traceback (most recent call last):
  File "GFN/main.py", line 309, in <module>
    run_exp_benchmark()
  File "GFN/main.py", line 267, in run_exp_benchmark
    run_exp_lib(create_n_filter_triples(datasets, feat_strs, nets,
  File "GFN/main.py", line 158, in run_exp_lib
    dataset = get_dataset(
  File "/GFN/datasets.py", line 35, in get_dataset
    pre_transform = FeatureExpander(
  File "/GFN/feature_expansion.py", line 27, in __init__
    super(FeatureExpander, self).__init__('add', 'source_to_target')
TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given
```
With the rest of the code untouched what could be the problem?
I would appreciate it if someone can find me an answer. Thank you

**Comment by ShenLongDX** [comment]
me too
